name: zig-build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
    - master
    - release/*
    - feature/*
  pull_request:
    branches:
    - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment: zig-build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      # Not necessary for this workflow, but useful for debugging
      - name: Install arm-none-eabi-gcc
        run: |
          sudo apt-get install -y gcc-arm-none-eabi clang-format
      
      # Get and install Clang 16 to build picolibc
      - name: Install Clang 16
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod u+x llvm.sh
          sudo ./llvm.sh 16
      
      # Not necessary for this workflow, but useful for debugging
      - name: Install Openssl
        run: |
          sudo apt-get install -y openssl

      # Installs dependencies using pip
      - name: Install deps
        run: |
          python -m pip install --upgrade pip setuptools wheel -r requirements.txt
          inv get-mcuboot-deps
      
      # Clean Zig build
      - name: Clean Zig build
        run: inv clean

      # Build picolibc
      - name: Build picolibc
        run: inv build-picolibc

      # Runs the Zig formatter and AST checker
      - name: Run Zig formatter
        run: python -m ziglang fmt --check --ast-check --color off .

      # Runs Zig using the Python environment
      - name: Run Zig program
        run: python -m ziglang build

      # Generate test private key
      - name: Generate test keys and sign firmware
        run: inv private-key sign-fw-images

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: embedded-files-${{ github.sha }}.zip
          path: |
            zig-out/firmware/*.elf
            zig-out/firmware/*.bin
            zig-out/firmware/*.hex
            signed/*.bin
            keys/*.pem
          if-no-files-found: error
          retention-days: 90
          compression-level: 0
